specVersion: 1.0.0
name: phala-world-subquery
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: '>=1.0.0'
  query:
    name: '@subql/query'
    version: '*'
description: Phala World Indexer for SubQuery
repository: 'https://github.com/Phala-Network/phala-world-subquery.git'
schema:
  file: ./schema.graphql
network:
  chainId: '0xdddd14809549577c006701f04d90c0a5221c959c59fccc24df9ca59ef1b52ab9'
  endpoint: 'ws://host.docker.internal:9944'
  dictionary: 'https://api.subquery.network/sq/subquery/khala-dictionary'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleOriginOfShellPreorder
          kind: substrate/EventHandler
          filter:
            module: pwNftSale
            method: OriginOfShellPreordered
        - handler: handleMintedOriginOfShell
          kind: substrate/EventHandler
          filter:
            module: pwNftSale
            method: OriginOfShellMinted
        - handler: handleStartedIncubation
          kind: substrate/EventHandler
          filter:
            module: pwIncubation
            method: StartedIncubation
        - handler: handleMintedShell
          kind: substrate/EventHandler
          filter:
            module: pwIncubation
            method: ShellAwakened
        - handler: handleFedOriginOfShell
          kind: substrate/EventHandler
          filter:
            module: pwIncubation
            method: OriginOfShellReceivedFood
        - handler: handleNftListed
          kind: substrate/EventHandler
          filter:
            module: rmrkMarket
            method: TokenListed
        - handler: handleUnlistedNft
          kind: substrate/EventHandler
          filter:
            module: rmrkMarket
            method: TokenUnlisted
        - handler: handleSoldNft
          kind: substrate/EventHandler
          filter:
            module: rmrkMarket
            method: TokenSold
